///////////////////////////////////////////////////////////
//  Vinculador.cs
//  Implementation of the Class Vinculador
//  Generated by Enterprise Architect
//  Created on:      12-Sep-2020 7:23:01 PM
//  Original author: Franco
///////////////////////////////////////////////////////////
using System.Collections.Generic;
using TPANUAL;
using TPANUAL.Clases.DAO;

public class Vinculador
{

	private List<Condicion> condiciones;
	private CriterioVinculador criterio;
	public List<Condicion> Condiciones { get => condiciones; set => condiciones = value; }
	public CriterioVinculador Criterio { get => criterio; set => criterio = value; }

	public Vinculador(List<Condicion> condiciones)
	{
		Condiciones = condiciones;
	}

	public void cambiarCriterio(CriterioVinculador criterio)
	{
		Criterio = criterio;
	}

	public void cambiarCriterio(List<CriterioVinculador> criterios)
	{
		Criterio = new Mix(criterios);
	}

	public bool cumpleCondiciones(OperacionDeEgreso opegreso, OperacionDeIngreso opingreso)
	{
		bool flag = true;
		foreach (Condicion condicion in Condiciones)
		{
			flag = flag && condicion.cumpleCondicion(opegreso, opingreso);
		}
		return flag;
	}

	public void vincular(int id_organizacion)
	{
		var contexto = new DB_Context();
		Organizacion organizacion = OrganizacionDAO.obtenerOrganizacion( id_organizacion);
		Criterio.vincular(contexto, organizacion);
	}

	public static void desvincular(int id_organizacion)
    {
		var contexto = new DB_Context();
		contexto.Database.ExecuteSqlCommand($@"
			UPDATE operaciondeegreso
			SET IngresoAsociado_ID_OperacionDeIngreso = null
			WHERE ID_Organizacion = {id_organizacion.ToString()};
		");
	}
}
