///////////////////////////////////////////////////////////
//  ML_CurrencyConversion.cs
//  Implementation of the Class ML_CurrencyConversion
//  Generated by Enterprise Architect
//  Created on:      04-Sep-2020 11:30:34 PM
//  Original author: Ignacio Andre Keiniger
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;




namespace TPANUAL {
	public class ML_CurrencyConversion {

		public DateTime creation_date;
		public String currency_base;
		public String currency_quote;
		public Double inv_rate;
		public Double rate;
		public Double ratio;
		public DateTime valid_until;

		public ML_CurrencyConversion(){

		}

		~ML_CurrencyConversion(){

		}

	}

}
