///////////////////////////////////////////////////////////
//  ML_Currency.cs
//  Implementation of the Class ML_Currency
//  Generated by Enterprise Architect
//  Created on:      04-Sep-2020 11:30:32 PM
//  Original author: Ignacio Andre Keiniger
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;

namespace TPANUAL {
	public class ML_Currency {
		public int decimal_places;
		public String description;
		public String id;
		public String symbol;
	}

}
