///////////////////////////////////////////////////////////
//  ML_Country.cs
//  Implementation of the Class ML_Country
//  Generated by Enterprise Architect
//  Created on:      04-Sep-2020 11:30:30 PM
//  Original author: Ignacio Andre Keiniger
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;

namespace TPANUAL {
	public class ML_Country {

		public String currency_id;
		public String decimal_separator;
		public ML_GeoInformation geo_information;
		public String id;
		public String locale;
		public String name;
		public List<ML_PlaceSmall> states;
		public String thousands_separator;
	}

}
