///////////////////////////////////////////////////////////
//  ML_GeoInformation.cs
//  Implementation of the Class ML_GeoInformation
//  Generated by Enterprise Architect
//  Created on:      04-Sep-2020 11:30:36 PM
//  Original author: Ignacio Andre Keiniger
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;

namespace TPANUAL {
	public class ML_GeoInformation {

		public ML_Location location;

		public ML_GeoInformation(){

		}

		~ML_GeoInformation(){

		}

	}

}
