///////////////////////////////////////////////////////////
//  ML_Location.cs
//  Implementation of the Class ML_Location
//  Generated by Enterprise Architect
//  Created on:      04-Sep-2020 11:30:38 PM
//  Original author: Ignacio Andre Keiniger
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace TPANUAL {
	public class ML_Location {

		public double latitude;
		public double longitude;

		public ML_Location(){

		}

		~ML_Location(){

		}

	}

}
