///////////////////////////////////////////////////////////
//  ML_PlaceSmall.cs
//  Implementation of the Class ML_PlaceSmall
//  Generated by Enterprise Architect
//  Created on:      04-Sep-2020 11:30:39 PM
//  Original author: Ignacio Andre Keiniger
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;




namespace TPANUAL {
	public class ML_PlaceSmall {

		public String id;
		public String name;

		public ML_PlaceSmall(){

		}

		~ML_PlaceSmall(){

		}

	}

}
