///////////////////////////////////////////////////////////
//  ML_State.cs
//  Implementation of the Class ML_State
//  Generated by Enterprise Architect
//  Created on:      04-Sep-2020 11:30:41 PM
//  Original author: Ignacio Andre Keiniger
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;




namespace TPANUAL {
	public class ML_State {

		public List<ML_PlaceSmall> cities;
		public ML_PlaceSmall country;
		public ML_GeoInformation geo_information;
		public String id;
		public String name;

		public ML_State(){

		}

		~ML_State(){

		}

	}

}
