///////////////////////////////////////////////////////////
//  Orden-Valor-PrimeroEgreso.cs
//  Implementation of the Class Orden-Valor-PrimeroEgreso
//  Generated by Enterprise Architect
//  Created on:      12-Sep-2020 7:23:03 PM
//  Original author: Franco
///////////////////////////////////////////////////////////
using System;
using System.Linq;
using TPANUAL;

public class Orden_Valor_PrimeroEgreso : CriterioVinculador {

	public Orden_Valor_PrimeroEgreso() {	}

	public override void vincular(DB_Context contexto, Organizacion organizacion){

		var listaIngresos = contexto.operacionDeIngreso
			.SqlQuery("Select * from operaciondeingreso where ID_Organizacion = {0} order by monto", organizacion.ID_Organizacion)
			.ToList();

		var listaEgresos = contexto.operacionDeEgreso
			.SqlQuery("Select * from operaciondeegreso where ID_Organizacion = {0} order by valortotal", organizacion.ID_Organizacion)
			.ToList();

		foreach(OperacionDeIngreso opingreso in listaIngresos)
        {
			foreach(OperacionDeEgreso opegreso in listaEgresos)
            {
				if (opingreso.Monto >= opegreso.ValorTotal 
					&& opegreso.IngresoAsociado is null 
					&& cumpleCondicionesVinculador(opegreso, opingreso))
				{
					// Guardo lo que me falta para llenar el ingreso
					opingreso.Monto -= opegreso.ValorTotal;

					// Si se puede, lo asocio
					asociarEgresoIngreso(contexto, opegreso, opingreso);

				}
			}
		}
	}
}