///////////////////////////////////////////////////////////
//  Orden-Valor-PrimeroIngreso.cs
//  Implementation of the Class Orden-Valor-PrimeroIngreso
//  Generated by Enterprise Architect
//  Created on:      12-Sep-2020 7:23:04 PM
//  Original author: Franco
///////////////////////////////////////////////////////////
using System;
using System.Collections.Generic;
using System.Linq;
using TPANUAL;

public class Orden_Valor_PrimeroIngreso : CriterioVinculador {

	public Orden_Valor_PrimeroIngreso(){

	}
	public override void vincular(DB_Context contexto, Organizacion organizacion){

		var listaIngresos = contexto.operacionDeIngreso
			.SqlQuery("Select * from operaciondeingreso where ID_Organizacion = {0} order by monto", organizacion.ID_Organizacion)
			.ToList();

		var listaEgresos = contexto.operacionDeEgreso
			.SqlQuery("Select * from operaciondeegreso where ID_Organizacion = {0} order by valortotal", organizacion.ID_Organizacion)
			.ToList();

        foreach (OperacionDeEgreso opegreso in listaEgresos)
		{ 
			foreach (OperacionDeIngreso opingreso in listaIngresos)
			{
				if ( opegreso.ValorTotal <= opingreso.Monto
					&& opegreso.IngresoAsociado is null 
					&& cumpleCondicionesVinculador(opegreso, opingreso))
				{
					// Guardo lo que me falta para llenar el ingreso
					opingreso.Monto -= opegreso.ValorTotal;
			
					// Si se puede, lo asocio
					asociarEgresoIngreso(contexto, opegreso, opingreso);

				}
			}
		}
	}
}