///////////////////////////////////////////////////////////
//  Condicion.cs
//  Implementation of the Class Condicion
//  Generated by Enterprise Architect
//  Created on:      12-Sep-2020 7:23:06 PM
//  Original author: Franco
///////////////////////////////////////////////////////////
using System.Collections.Generic;
using TPANUAL;

public abstract class Condicion {

	public Condicion(){

	}

	public abstract bool cumpleCondicion(OperacionDeEgreso opegreso, OperacionDeIngreso opingreso);

}//end Condicion